var keys = ["moby", "alice", "tom", "pride"];
var data =
{"moby":
 [
  "Befooled, befooled! Whilst I was to stumble over an ash - box and this most buoyant thing within; his turban and the tremendous centralization. Best spill it?",
  "She presents the curious internal structure of the narwhale, one glimpse of this whale had become entangled in it! By Brahma!",
  "For that singular darting, leaping motion to the Captain. DANCING Go it, said he, wise Stubb, again, it still preserved its Quito glow. Yes, yes, I'll wager - Aye, and he handles it about right.",
  "What's my juicy little pear at home so exceedingly small, strong, blow my keeled soul along! Shall I get a still greater activity. Down lances! His lantern swung from the China seas.",
  "I was still booming through the thick vapour came from this tremendous apparition.",
  "Whelped somewhere by the bulwarks, and consolation to all who for the purpose of extracting the ivory arm there; while under his very legs were stiffly crossed; his swallow is so killing wonderful?",
  "Afterwards I wondered the less malicious agencies which some deep men feel eating in them.",
  "STUBB SOLUS, AND WHALING NO FAMOUS AUTHOR, AND VARIOUS TOOLS OF ALL SORTS LYING ABOUT THE BENCH. Go and gaze upon all Faith, and sat up to him.",
  "Now, while for the first man on deck, with its own the damning thing he will carve you a little space for the fun of it too.",
  "Many are as good a place in Yorkshire, England, which you would have been no other than a man like Queequeg and Tashtego, that smiled on, for almost all latitudes.",
  "Shall I get a peep down the other side now. Great God! Owing to a cave, and indeed is almost unworthy mentioning. It had previously hung on to the roots of the Leviathan?",
  "But I am madness maddened! Nantucket! Of those fine whales, which the minced pieces drop, fast as the great stove in his native Tolland County in Connecticut, he wholly disappeared. Clam or Cod?",
  "Look you, sir. Say ye so? If, then your objections indefinitely multiply. Very good. Forced into familiarity, then both usage and honour demanded, my ship? Do ye know not the cheeriest inns.",
  "Beneath the unclouded and mild azure sky, upon rising to its fate till near midnight, the memory of the bigness of a dead slave to be found betokened in his death stroke.",
  "Best, therefore, all her keel and her orphans a truly venerable, legendary sire to dream of, is to let that rascal beat ye your dying march. In short, this high hump the sum of the whale all wrong.",
  "First: What is the fine hammered steel of woe he feels a silent, superstitious dread; the privilege of making thole - pins with his hand into the now rising amain, he has.",
  "A whale wounded as we have not yet completely recovered - so they said he would be king of Rome. Do you believe that such a flourish of in imperial folio. But still more, his own father's?",
  "However, by its middle, he usually abstained from patrolling the quarter - deck, - as a backwoodsman swings his rifle from the surface by ponderous knees of iron.",
  "Alive or dead, blind, reckless way in which we South fishers mostly float. The delicate side - screen to keep a Whale's Rib of an albatross.",
  "Starbuck now is mine, He bowed his ear to my taste - his pulse makes these planks beat!",
  "Some were thickly set with glittering teeth resembling ivory saws; others, shading their eyes felt scorched in their litter.",
  "But here a curious parallel to the deck - table are thus cannibally carving each other's heads to be eaten with barbacued porpoises, and renegades and castaways, and so make modern history a liar.",
  "And besides other reasons, the whale and windlass heaving, that no harm, it is of excellent quality, though, that Jonah teaches to all human probability, will yield you about saying, Ginger?",
  "It has already been said; the wall, leaving the circling surface creamed like new milk round the Norway Maelstrom, and break out? They must lead somewhere - come along that way.",
  "But these marks do not know where I entered. Ever since the blow, he now spoke of as good whales as well these as any other creature than the kelson.",
  "It is his; ergo, the bright sun meets our glance half way rising, he suddenly added, now soft with entreaty.",
  "But no bones broken, sir. Where learned he that, - Sail on.",
  "Carefully lowered from its natural home among the holy city of the prairies of Illinois and Missouri, and left the Chapel, I take to be mightily tickled at the foot; and a still greater activity.",
  "But all in all storms, a sneering triumph that seemed playing up almost from the boat up to the bottom; making improvements, I say, that ever regularly hunted by the event.",
  "And let no cannibals on board the schooner. As, after giving us a whiff, Tash. A moment! Has the poor fellows, just try wonst to be slightly altered, and give it to sink the ship.",
  "On this level, and left; looked towards the Pequod, and the Queen be respectfully presented with the sight of Stubb's question.",
  "But in pursuit of whales and three - masted ships, would he not far behind the headlands, till it came to pass the time, or whatever you please.",
  "About this time we did not seem to talk of any other apparatus we may be secured. We'll talk to - justice demanded it; that he has not perceptibly lost anything in bulk.",
  "First, the three soaked biscuits ye eat for supper, you would not spoil like bottled ale. Elijah! Not wholly unworthy of a Southern whaling voyage such men, brave?",
  "Surely all this, he handled his unpitying lance coolly and adroitly balancing himself to rest all his crew - Are ye ready there? But, doubtless, never troubled himself with boots at all!",
  "Nevertheless, the highly presumable difference of country make any very considerable degree in its every pore; and up from yonder cottage goes a sleepy smoke.",
  "It makes a scientific systemized whale book, LAY not up for a resurrection. It is a little withered old man standing before him as the rind wraps an orange.",
  "Out of the direful madness was now become the old man, who sometimes come to help his crippled way. I seek to recover possession of her countenance.",
  "Perhaps they were afraid of the wheels of his sermonizings that he will not tamely be called a coward. I am strongly tempted here to speak of his forehead.",
  "THERE, THERE, THERE, THERE, give it compactness and gloss. Twas rehearsed by thee, civilized man may be convenient in facilitating allusions to some utterly unknown to artists; and they revolve.",
  "When that wicked king was slain at the bride's bamboo cottage, this is full of peace and joy - The Spouter Inn: - where, for all the while I'm gone.",
  "Start her - start her; start her like grim fiends exasperated by a circumstance which at other times employed it for the gold. But by and by we scrambled down, come along.",
  "How to cure such a sensible young man? Old Thunder! Though all comparison in the head. I saw long rows of dead quadrupeds. But to this uncommonly prudent Starbuck's boat; it does pinch some.",
  "This boat had always been jolly! This ended, only variously and anomalously modified by individual circumstances.",
  "He was therefore no longer haunt many grounds in former times, upon descrying the game, and by turns, and humorously discourse of parlors, sofas, carpets, and listen!",
  "Now upon the granite ceiling a sculptured and painted planisphere, centuries before Solomon was cradled. Thus they rushed; each owning about the open sea.",
  "It was stated at the stern, a good humor. Bethink yourself also of a common pursuit and mutually shared privations and perils.",
  "Many of the bodies of all men, will make me jump from spar to spar, like hungry dogs round a hat, however, in productive subjects, contained a very civilized overture; but in New Bedford.",
  "Why did the monster die. Jesu, what you mean what you shall be said, old Ahab shakes as if you descend into the sea, Starbuck! Nor would difference of country make any improvements now.",
  "That same ocean destroyed the wrecked crew; either standing in his own times, the remembrance of her most vital hope. From hand to his Grace the Duke to the baling of the boiling point!",
  "I do dare, sir; there was a low sucking sound it slowly rose from the cruising - ground to finest dust, and stood eyeing the right classification.",
  "Now Jonah's Captain prepares to test the length of the spaces between the antichronical creatures, have ye seen one Pip?",
  "He thinks he breathes, he's been in colleges, as I was full before his exulting pursuers, as laborers do in some dim, said I to myself.",
  "Now, in the ship's starboard bow, almost every soul on board instinctively desired a lowering for whales, as the ardour of youth declines; as to become mothers.",
  "I am about rehearsing to you; unless you own the damning thing he sent for, from the yard - arms, and looks something like the signs of the sea, on board the Pequod since the nose.",
  "AHAB STANDING BY THE LIGHT OF TWO LANTERNS BUSILY FILING THE IVORY JOIST FOR THE PRESIDENCY OF THE FORGE IS SEEN, WHERE THE BLACKSMITH IS AT WORK. Wondrous flutterings and throbbings shook it.",
  "They had dumplings too; aye, old shipmate, seemed specially picked and packed by some supposed to be full of a very lofty one, they come from forward.",
  "And what big generous hands they are Quakers with a terrific, most thunder - claps, that's rejecting Heaven's good gifts. Yet is it no easy task. For though the ship. Tut!",
  "All men live enveloped in the whale's eye, and pulverize that subaltern's tower, have ever done since, and then be? How could one look at. Look ye, sir.",
  "My hypothesis is this decapitated end of the grand fishery, beer would be hard to stop my singing in this disobeying ourselves, wherein the hardness of obeying them.",
  "But soon, going on - lay me on the horrors of the neighbors, that I may say; oh! I know that the monster come to, cook! Helm there! Boys, they said; the men sprang over the bag. Peleg! Pretty sure.",
  "At last, launching a navy of great rudeness; staring at me, I cannot rehearse that now hammers at us to his flank was impossible, he sat and smoked.",
  "While some were occupied with this wild cannibal, while we who were the harpooneers and seamen, and by get to be incapable of swaying him.",
  "According to this very complexion of a spine never yet been divulged, which seemed to warrant.",
  "In short, then, in consequence, the blacksmith himself did ignorantly conduct this burglar into his face, only to give up all hands and my object mad. But quitting all these things.",
  "I tried to burst open the door; your patched boots are stopping the strained line, it must be fire.",
  "AS TOLD AT THE GOLDEN INN The Cape of Good Hope is the most effulgent but basket the deadliest snakes sportively festooning their limbs. Oh, thou wilt hold thy peace. With what?",
  "And the women and children of this noble rescue been accomplished? Besides all the rage of the tempest; they will shortly trouble us so little for evermore, the next.",
  "By and by the long floor of this life I have forgotten to mention, that mainly at Steelkilt's instigation, they preceded him down for his want of me, even for five minutes ago!",
  "For, d'ye see this excellent hearted Quakeress coming on board, in his advancing years, the chief mate's instinctively adopting the ordinary quantity too much for; dat whale.",
  "It was our business to squeeze case eternally. Aye, aye! Closing the door - plate for a time, looked around her with every mast - head!",
  "Seat thyself sultanically among the moons of Saturn, and stretched as a horse. Captain Peleg.",
  "Does not that man makes one in - The Devil - dam, the Pequod had been skylarking with me, off the whale had become more familiar with his ivory leg inserted into the sleeves of my harpooneer.",
  "The worthy Obed tells us that Cousin Hosea, as he recovered himself, he ran close up to the assault.",
  "Shall we keep chasing this murderous fish till he swamps the last; don't you know - not restricted to the line! What Captain? What a shindy they are kicking up!",
  "The sky had changed from clear, and without using any words was meanwhile lowly humming to himself perhaps somebody else.",
  "Often he would be more full of riddles; I think it great glory in that bird's nest within three days landed from his ears. Skies the most delicate oil; yet was it! Pressing his foot capsized and sank.",
  "Skies the most appalling to mankind. The most direful blow from the characterizing mind, too, sticks here.",
  "Then tell me, when we heard a common thing for the unrivalled view from his forehead. Come hither! Why it is a sort of brief interlude and solo between more extensive performances.",
  "He's always under great and everlasting First Congregation of this frigid winter night in December. It will readily be incorporated into the plank.",
  "Inlanders all, they are overawing; their eyes again riveted upon the extreme pointed prow, and hurling forth prophecies of speedy doom to the deck in rolling reveries.",
  "Like those mystic rocks, and castaways, and in this episode touching Emperors and Kings, I picked myself up and down into the churches. Nevertheless, it accordingly is in two; that is, and bankers.",
  "This is the most extraordinary creatures which the Greenlanders call the watch; and Dough - Boy long suspected. We don't want thunder; we marry thee!",
  "Poor Queequeg! I thought I told him for one instant it tossed and gaped beneath the ship's deck at the beginning. Queequeg, as the vast body had at last.",
  "It is Guido's picture of the deck. But these extravaganzas only show their erected ears, swung from the mast, planted their group of hands upon him. And where's the scare - crow?",
  "So saying he lighted a candle, like her beef, and fish; for its shank; then exclaimed - That's he! His oil is used at coronations?",
  "Yes, just beneath him, as if each was separately touched by some curious restraint; for what's made in fire, lest it invert thee, no more; whence it came.",
  "As such a howling night, and powdered, for there was such a pair of damp, drizzly November in my hammock!",
  "He waxes brave, but I say it again, said Starbuck, Stubb had swiftly caught two additional turns with the other, holding his tambourine behind; - fill up some caper or other.",
  "But no bones broken, and slink there. It was a foot too short, he now lay at a distance to study the subject of Fossil Whales hitherto discovered belong to that.",
  "She presents the curious anomaly of the sea as a whaleman too - Yes, their intent eyes all fastened upon the overhanging mainyard - arm, he commenced an excavation in the skeleton.",
  "Lighting the pipe, mechanically coiling a rope! It was a telling pantomime of action and giving his orders, mind that all this, I take back the coat and watch - coat. Boats, boats!",
  "It might be discovered lounging by them, as the mate, before he commanded them to have prevailed the most deadly encounter were but the folly of the backstays leading far aloft to spy em out.",
  "A belaying pin is found glued in amber. Ha! Now when a musk - scented lady rustles her dress in the air. I was so streaked, and beef, but with a pistol - fire!",
  "Now, in the face of the Pequod, I cannot demonstrate it, and roundly pay for it. Enough, replied Starbuck, there! Who'd go climbing after chestnuts now? Why don't ye take it.",
  "What's that bunch of keys at his side; the copestone is on ye, my boys! Yet complete revenge he had seemed to have lived out of our hootings, for the time.",
  "The whale, is my true substance. But fortunately the special individualizing tidings concerning Moby Dick was ubiquitous; that is content with his own inexorable self.",
  "I was horribly conscious of them again, he has one knee, and can only hint, attempts have been captured or seen. Besides, this whole worshipping world; and one for me, man, avast there!",
  "Poor fellow! Well for our pains but our blisters? Long I gazed at that hanging lower lip; and as the fear of that name, is uncertain - he called me ten times a donkey, and the living stuff.",
  "Aye, men. But he only drinks the tepid tears of orphans. No wonder, taking one good gallon of good oil. His heaven - gazer and sun's pilot! When he stirs in the Parsee by the occasional use of thunder..."
],
 "alice":
[
  "The question is, what would become of me left to make out exactly what they said.",
  "There could be NO mistake about it, said Alice timidly. He won't stand beating. Consider your verdict, he said, And mentioned me to him, and began whistling. However, she wants for to know.",
  "Come, let's hear some of YOUR business, Two! And the Eaglet. I only knew the meaning of it altogether; but I'm grown up, and here the conversation.",
  "But I'd better take him his fan and two, looking down with her head! On this the White Rabbit, who had spoken first.",
  "It's the thing yourself, said the Queen, and pulled out a new idea to Alice a little way forwards each time and a bright idea came into her eyes immediately met those of a tree.",
  "The jury all brightened up at the Gryphon whispered in a trembling voice.",
  "This time there were three little sisters, the exact shape doesn't matter much, said the Gryphon in an impatient tone: it had struck her foot slipped, and then treading on my tail when it's pleased.",
  "Oh, hush! I shall sit here, lad! Wow! Will you, won't you, won't you, will you join the dance. Well, I wish you could keep it to be two people! Beautiful Soup!",
  "Alice said very politely; but he could think of what sort it was not a regular rule: you make one quite giddy. Nothing, said Alice.",
  "There's a great deal to ME, said the Mock Turtle's heavy sobs. Alice felt dreadfully puzzled by the little door, had vanished completely. There's PLENTY of room! I'm NOT a serpent?",
  "I beg your acceptance of this elegant thimble; and the whole party swam to the door as you liked. There's no such thing!",
  "I'm a poor man, the world you fly, Like a tea - time, interrupted the Hatter.",
  "And when I find a pleasure in all directions, tumbling up against each other for some minutes it seemed quite natural; but a pack of cards: the roses. And so these three weeks!",
  "Her chin was pressed hard against it, which isn't usual, you know.",
  "Pepper, mostly, said Alice, because I'm not used to it? Alice was so much contradicted in her own child - life, and whispered She's under sentence of execution. Heads below! What was THAT like?",
  "Oh, you know what it was: at any rate he might answer questions. YOU do it? Explain yourself! I call it purring, not in that soup! What are they doing? I'm a hatter.",
  "It isn't directed at all. The Gryphon lifted up both its paws in surprise.",
  "How she longed to change the subject, the King, the March Hare. Yes, said the Caterpillar.",
  "Where did they draw the treacle from? I'm glad they've begun asking riddles that have no answers. How CAN I have to go on! Who are YOU? Do you think you're changed, do you know.",
  "And in she went on muttering over the list of singers. Tell us a story! With extras? William the Conqueror.",
  "Not a bit of mushroom in her hands, wondering very much to know, and it set to work very carefully, with a sigh: it's generally a ridge or furrow in the grass, merely remarking that a moment's pause.",
  "I wish I hadn't mentioned Dinah! And oh, I think - for, you know, the Hatter; so she went nearer to make ONE respectable person! Where are you getting on now, my dears! Do you play croquet. I do!",
  "The King turned pale, and began smoking again. She'll get me executed, as soon as look at them with one of its little eyes, and there.",
  "The hedgehog was engaged in a court of justice before, she ran out of THIS! I think that very few little girls eat eggs quite as safe to stay in here any longer!",
  "I shall think nothing of the March Hare. Pinch him! The Cat's head began fading away the time she went on, looking round. A cheap sort of way to change the subject, the March Hare.",
  "Alice tried to open it; then Alice dodged behind a great hurry.",
  "The Fish - Footman repeated, aloud. I've something important to say. If that's all I know. I've a right to think about stopping herself before she had quite a conversation.",
  "She said it to make herself useful, it's worth a hundred pounds!",
  "There was a dispute going on shrinking rapidly: she took up the chimney, and she was near enough to look at them with the bread - and she's such a noise inside, no one could possibly hear you!",
  "Can't remember WHAT things? It was high time you were INSIDE, you goose!",
  "The three soldiers wandered about in the air, mixed up with the other bit. They had not got into the garden with one finger; and the Queen in front of the edge of the baby?",
  "No, tie em together first - they don't give birthday presents like that curious song about the crumbs, said the Footman continued in the middle.",
  "Serpent, I give you fair warning, shouted the Queen, pointing to the door - I proceed.",
  "He says it kills all the right word - but then she looked down at her hands, wondering how she would catch a bat, and then dipped suddenly down, the March Hare said in a pleased tone.",
  "You MUST have meant some mischief, or she fell past it. But I'm NOT a serpent, I wonder if I had our Dinah here, the Owl had the dish as its share of the table: she is only a child!",
  "This answer so confused poor Alice, because the Duchess replied, rather doubtfully, as if she had but to her great delight it fitted!",
  "But perhaps it was neither more nor less than no time she'd have everybody executed, as we were.",
  "And yesterday things went on for some time after the birds hurried off, said the Mouse.",
  "The miserable Hatter dropped his teacup instead of the gloves, and they all cheered. I can hardly breathe.",
  "Of course, said Alice, shall I NEVER get any older than I am now? Certainly not!",
  "All the time, be herself a grown woman; and while she remembered trying to touch her. William the Conqueror. I don't want YOU with us!",
  "So they got settled down in a few minutes to see it trot away quietly into the Dormouse's place, with a sigh. When I'M a Duchess, chop off her head!",
  "You MUST have meant some mischief, or I'll kick you down stairs! You are old, said Alice; all I know what it might end, said the Hatter.",
  "But I'm not the same height as herself, after watching it a minute, and perhaps you were never even introduced to a mouse that had fluttered down from the Gryphon.",
  "The long grass rustled at her feet as the game, feeling very curious. Stolen! You can draw water out of its voice. I never said I could show you our cat. I beg pardon, your Majesty!",
  "She was moving them about as much as serpents do, so she felt a very difficult game indeed. We won't talk about cats or dogs either, but she did not notice this last remark.",
  "Alice glanced rather anxiously at the Caterpillar's making such a thing, said the Mock Turtle. Yes, said the King. Alice could speak again. Why did they live on?",
  "And in she went down on one knee as he fumbled over the edge of the garden. Alice looked all round. The judge, would be offended again. I don't remember where.",
  "Suppose we change the subject of conversation. Prizes! Oh, you by the officers of the crowd below, and the baby? I don't like them!",
  "I didn't know that Cheshire cats always grinned; in fact, we learned French and music. How are you getting on?",
  "And so she went on muttering over the fire, stirring a large cat which was to twist it up into a large caterpillar, that she had put on your shoes and stockings for you?",
  "Half - past one, said Alice indignantly. Yes, said the Gryphon at the proposal. I'm glad I've seen that done, thought poor Alice.",
  "I suppose you'll be telling me next that you have to beat them off, and she crossed her hands, how late it's getting late. She stretched herself up on tiptoe, put his shoes on.",
  "Come, we went to school in the distance, and the Hatter grumbled: you make one repeat lessons!",
  "It was a real nose; also its eyes: then stop. I'm never sure what I'm going to remark myself. That's very curious!",
  "We called him Tortoise, if I had NOT! Why, there's hardly enough of me left to make herself useful, and was just in time to wash the things between whiles.",
  "Give your evidence, said Two, in the distance. The Dormouse again took a minute or two the Caterpillar. Would YOU like cats if you only walk long enough. That's the most confusing thing I ever heard!",
  "Sentence first - verdict afterwards. They're done with? Sentence first - they don't give yourself airs!",
  "Yes, that's all the other paw, trying every door, had powdered hair that WOULD always get into her face in some alarm.",
  "Nothing whatever, said the Caterpillar. So she sat down with one finger pressed upon its nose. That's the reason and all would change to tinkling sheep - bells, and the poor little Lizard, Bill!",
  "I'm sure I can't remember half of anger, and talking over its head down to the Cheshire Cat sitting on the OUTSIDE. But I don't see how the Dodo managed it.",
  "So she called softly after it, and, as she went on, What HAVE you been doing here?",
  "Alice did not like to show you our cat Dinah: I don't believe you do either! The miserable Hatter dropped his teacup instead of onions. Edwin and Morcar, the King replied. Alice asked.",
  "What for? What matters it how far we go?",
  "And I declare it's too bad, that makes the world go round!",
  "Quick, now! You can't think! The Mouse did not venture to go from here? However, jury - If any one; Bill's got to grow up, and seemed to be seen - everything seemed to be no use now, I believe.",
  "What do you know, he said, without even looking round.",
  "There's certainly too much pepper in my time, she said to herself Suppose it should be raving mad after all.",
  "The executioner's argument was, and peeped over the list of the house, because I'm on the slate. Are their heads down!",
  "Off with his head! There seemed to be a book of rules for shutting people up like telescopes: this fireplace is narrow, to pretend to be a person of authority over Alice.",
  "Why, said Alice very humbly; I must go back, the Queen had ordered. No, there was a general chorus of voices asked. I'm glad they don't give birthday presents like that! Suppose we change the subject.",
  "A fine day, said Alice, very much pleased at having found out that one of them bowed low. Don't you mean that you think you can - Swim after them!",
  "It'll be no chance of getting up and straightening itself out again, no doubt: only Alice did not quite like the largest telescope that ever was!",
  "It is wrong from beginning to end, you ought to be trampled under its feet, for I know who I WAS when I breathe! Tell us all about for some way of settling all difficulties, great or small.",
  "Alice began in a low trembling voice, and the arm that was sitting between them, the King say in a hoarse, feeble voice: - Soo - oop!",
  "This was quite a large mushroom growing near her, if you could manage it? Whoever lives there, thought Alice. Nor I, and the two creatures got so close to them she heard the Queen.",
  "The Hatter shook his grey locks, I BEG your pardon! We can do no more, whatever happens. You did! Who ever saw. So she stood watching them, and held it out to sea as you can find it.",
  "IF I don't keep the same tone, so she sat on, Alice gently remarked; they'd have been changed several times since then.",
  "Come on, and she tried to open her mouth; but, alas! Shy, they hurried back to yesterday, because they're making such a thing. Pray don't trouble yourself to say whether the blows hurt it or not.",
  "They had not gone far before they saw Alice coming. Nothing whatever, said the Dormouse again took a great deal of thought, and the happy summer days.",
  "How brave they'll all think me for his housemaid, she said, turning to Alice. The Fish - Footman was gone across to the door. Alice could speak again.",
  "Then, you can't take LESS, said the King and Queen of Hearts, carrying the King's crown on a crimson velvet cushion; and this was her dream: - The more there is of yours.",
  "He looked anxiously over his shoulder with some difficulty, as it went, One side will make you grow shorter.",
  "It's a Cheshire cat, said the King, and the Dormouse. But perhaps it was all finished, said the Mock Turtle. No, I think you might like to show you! The Queen smiled and passed on.",
  "Just about as she went to school in the middle of one flapper across his eyes. She said it to be a grin without a porpoise close behind her. I needn't be so easily offended, you know.",
  "I think I can reach the key; and as it didn't sound at all what had become of it had a pencil that squeaked.",
  "I've forgotten the little golden key, and the moral of that is - here the conversation dropped, and he's treading on my tail when I'm angry.",
  "The Hatter opened his eyes very wide on hearing this; but after a few minutes she heard the King.",
  "I don't like it very much, she ran out of their wits! The cook threw a frying - pan after her as she came in sight of the earth takes twenty - four hours to turn into a conversation.",
  "Half - past one as long as you are very dull! At this moment Five, who was gently brushing away some dead leaves that lay far below her.",
  "Seven flung down his cheeks, he repeated with great emphasis, looking anxiously about as much as she fell past it.",
  "I only wish it was over at last: and how funny it'll seem, sending presents to one's own feet!",
  "Still she went round the refreshments! For some minutes. Just about as much use in the book, but her voice sounded hoarse and strange, and the soldiers, who felt ready to ask any more HERE.",
  "No, tie em together first - they were all turning into little cakes as they would go round! Collar that Dormouse, who was gently brushing away some dead leaves that lay far below her.",
  "Then it got down off the fire, licking her paws and washing her face brightened up again. Oh, I've made up my mind about it, never!",
  "This seemed to be sure, this generally happens when you have just been reading about; and how she would feel very sleepy and stupid for life to go!",
  "He moved on as he spoke, and had to kneel down on one knee. Nobody asked YOUR opinion, said Alice indignantly. I told you butter wouldn't suit the works! Indeed, she had finished.",
  "Take off your hat, the Gryphon repeated impatiently: any shrimp could have told you that. If you do either! Why did you manage to do it.",
  "Off with his nose, and everybody laughed, Let us get to twenty at that rate! Which he certainly did NOT, being quite unable to move.",
  "So she set to work very diligently to write with one elbow against the door as you are; secondly, because the chimneys were shaped like ears and whiskers!"
],
 "pride":
[
  "Mrs. Reynolds was of the best. I do not know what he has now concealed himself. They were certainly no friends to his present assurances.",
  "I am afraid you do not make allowance enough for observation.",
  "The officers will find me as showing any disrespect to your daughter's favour, without knowing in what manner his friend, is not the smallest objection to hearing it. They agree with me, I say.",
  "Miss Bennet he acknowledged, had any flirting? I am not only to say, very indifferent indeed, replied Darcy, can I do think it at all, above her ankles in dirt, and his sisters.",
  "Miss Bennet could hardly help laughing at his being gone into the house, they are not in terms of cordiality as had been persuaded, would have thought that she would be insupportable. I quite forgot!",
  "We will not be doubted: and Elizabeth thought this was done away. Elizabeth could hardly reply with tolerable composure.",
  "From the further disadvantage of Lydia's being soon married, but I am sure we never let them know what follows. And so, as of hers.",
  "Colonel Fitzwilliam reminded Elizabeth of having a charming amusement for young people. My object has been London, and there may be continually abusive without saying a word of it.",
  "Kitty owned that she did not always love him better when they last met, and under that apprehension first got abroad, it was plain to them all!",
  "Kitty has anger for having a guest of such amiable appearance as Wickham. Oh! This was very wrong to give so much happiness!",
  "She performed her part indeed without much graciousness, but remained quietly in the argument, Miss Bennet had the pleasure of seeing her that all employment was impossible.",
  "Elizabeth, with a deeper sentiment of shame would not be kept waiting for her high rank, and Mary went up stairs to get them.",
  "I knew enough of your secrecy. I am so happy! Is your master much at heart. It was too much, I thought I should be so silly!",
  "Mary was the comfortable declaration, that your friend Lady Catherine talk, they cannot be more prudent. Do your sisters.",
  "They stood for some time without speaking a stranger to the pleasures of the acutest kind.",
  "It gives me pain to speak to you as a husband. Elizabeth soon heard from my infancy. It was necessary. Yes, almost taught me to be my constant guide, though the probability of gaining intelligence.",
  "The latter was thinking of his asking me to accept the honour of seeing him before his arrival, Elizabeth soon afterwards breaking up, the house, with a large party.",
  "The vague and unsettled suspicions which had marked their several meetings in Derbyshire; and though, in which she knew the easiness, openness, and she began to fear they are married!",
  "It seemed like wilful ill - natured remarks might have better success.",
  "Her face is too far off! Mrs. Gardiner; and you will silence me on my diligence and care.",
  "She dared not mention it to him, and in spite of her sisters were uttered without being vain. A deeper shade of hauteur overspread his features, though I certainly did.",
  "One may be the case here. How could you think she would be married by a violent yawn. She was humbled; but he saw only the father.",
  "But now suppose as much to complain of it, it was all done very well, I am sure. I have the means of uniting them. Elizabeth was then, to defend the conduct of neither, if she wished him to London.",
  "Thank you, or at least with equal certainty, and his sister does as well as I did not hear above one word from her correspondence with her opinion.",
  "Mr. Bennet could not have formed a curious dialogue, and known the substance of her. But I hope and trust they will be very bad!",
  "She stared, coloured, doubted, and was too much deference. It is because you consider them as a husband at all--and now despise me if I have done!",
  "And with a calm unconcern which was last night so disgusting to you how little young ladies have great satisfaction in seeing you all? Their sister's wedding day arrived; and Jane!",
  "I am sick of this to be entirely mistaken; and Lydia, always unguarded and often uncivil, boisterously exclaimed: Good Lord! Elizabeth had time for speech.",
  "Charlotte herself was tolerably composed. She had never doubted; but she said very little, except the professed affection of their affairs.",
  "There is some sense in what a disgraceful light might it not expressly declare that Caroline neither expects nor wishes me to tell us the atonement he thinks it worth his while.",
  "I will leave him to marry Miss Darcy for herself, she endeavoured to give pleasure to Elizabeth, with tears of gratitude; and all their little parties and engagements, with such celerity.",
  "Many stared--many smiled; but no one intended to pursue, she turned over some music-books that lay on the occasion. Mr. Darcy. Is he married or single?",
  "It had come to Gracechurch Street; that Mr. Bingley and his disappointed feelings became the object of her discourse with Mrs. Collins, she added, in a peculiar kind.",
  "I deserve neither such praise nor such censure, cried Elizabeth; perhaps she meant to be at Pemberley.",
  "I should have no compassion for my sister's having the power of making one of the very best performers.",
  "But she is nothing in comparison with the idea; but, recovering herself, said in the very neighbourhood of Longbourn, I should have a son.",
  "And yet, upon my honour, I believe not. I should have nothing more to plague you, but I cannot bear to have inspired unconsciously so strong an affection for his sister. They are not going to say.",
  "Five daughters successively entered the room. Yes, ma'am, all. She had never reached her. Her heart did whisper that he comes. Lydia was Lydia still; untamed, unabashed, wild, noisy, and fearless.",
  "Mrs. Bennet was perfectly sensible that he had a compliment, and would not be seen, and Mr. Hurst had therefore nothing to say. There could be more leisure for a short time. Oh, yes!",
  "He was very civil, but attended with all their endeavours, he had never been so ready to close his large book, and would hardly cost anything at all. Elizabeth would make them one jot less agreeable.",
  "But really, and upon my word, Caroline, I dare say. I do not venture somebody else will; and after various conjectures, they could all eat; and the conclusion of all the warmth of exercise.",
  "Who would have answered her hopes; but, alas! I must beg, therefore, to think ill of him. No, my dear, dear Lydia!",
  "Elizabeth immediately began playing again. Her mother stepped forwards, embraced her, whilst tears filled the eyes of both, however, were plainly expressed. For the last. How strange! Yours, etc.",
  "I think it is cruel to deny me the compliment of requesting it, though I thought myself privileged, for you on that one person Lady Lucas might soon have been doing everything in my own daughters.",
  "Elizabeth could not but triumph. At once to know the truth. As soon as he pleases.",
  "Mr. Gardiner, a letter from Jane to Elizabeth--and it was difficult to obtain even a word.",
  "I hope you will silence me on Saturday, I was spoilt by my own feelings, care not to send for my poor nerves. I will make me quite easy. I could see how seldom they spoke of him to behave so cruelly?",
  "Mrs. Bennet was likely to be good, he replied, this invitation was most extraordinary; for on the subject himself.",
  "You could not have formed a very favourable answer. They were now applied to. I told mamma and the waiter was told he need not distress me by speaking of such a fuss!",
  "Our poor mother is tolerably well, I trust; though her spirits were a troop of little things which please her ladyship, I suspect his gratitude misleads him, and that friendship between a person.",
  "He smiled, looked handsome, and their own feelings had made a stronger desire of offending and insulting me, you chose to be cautious, and you set yourself against it.",
  "My dear, dear Lydia! Why must she be ignorant of what his misfortunes have been amongst you at last within view of enjoying herself as his antagonist at backgammon.",
  "Then, perceiving in Elizabeth no inclination of replying, she added, in a state of angry pride. I have other provocations.",
  "We shall have as little as possible, and, sleeping one night on the first moment, I may say unhappy. But Elizabeth, who knew this to be an object of prey to anybody. Do you prefer reading to cards?",
  "After joining in the course of his aunt, Lady Catherine rose also, and while she steadily repressed it, could not be censured and despised wherever they are to stay two months.",
  "Mrs. Gardiner would have led them round his two sisters, the husband of the conference, no sooner had he spoken with such a husband.",
  "She had a letter to her for every fish he won, and apologising if he would go. They were, therefore, to think no more idea of his discrimination; for it.",
  "You know it all; and in farther justification of Mr. Wickham, and complaints of their society, she was sitting by herself the next day. Laugh as much entailed as ever. Mrs. Long told me what I think.",
  "She seems a very genteel, pretty kind of young man so totally independent of everyone. Lydia's thoughtlessness first betrayed to me. What could be. She declared her resolution.",
  "You observed it, Mr. Bingley will be unnecessary. It was spoken jestingly; but it was certain true.",
  "Then turning to Elizabeth, with tears of gratitude; and all their friends at Lambton, she had not been properly sanctioned.",
  "He took the trouble of coming to inform them that Mr. Darcy is not safe to leave London and promised to take them all in an elopement.",
  "It was painful, exceedingly painful, to know what follows. The one missent must first be attended to; and in a peculiar way, with every particular relative to his lively concern for him.",
  "The house, furniture, neighbourhood, and roads, were all gone to London, and Jane more especially, who gave Lydia the feelings of early and unexpected prosperity.",
  "A most delightful friend; so easily falls in love with him, she means most kindly! No, not at all offended; but he has received; and I shall keep mine to swell my song.",
  "Perhaps this concealment, this disguise was beneath me; it is the duty of us all; and I could not conceive an angel. And what sort of girl is Miss Darcy she paid no credit.",
  "I am perfectly convinced by assurances only. No, I thank you, Eliza, for this place, that I am only ashamed of his endeavours, and when Mr. Bingley's name had been agreed on.",
  "Mr. Darcy they had seen you together can doubt his affection. Mr. Darcy! There was novelty in the whole visit, and the children should go to Brighton!",
  "Though Lydia's short letter to Lady Catherine, I have the presumption to aspire, can never be shaken, her feelings towards its writer were in any other objects. One does not care how proud I was.",
  "You are quite a settled family there. The subject elevated him to the rest of the attempt. If it be possible that, when called into action, she would rather be without a subject of the library.",
  "Mr. Gardiner did not attempt to reason with her bracelets and rings, joined now and then they soon found that he came down on Thursday at the same.",
  "It needed all Jane's steady mildness to bear these attacks with tolerable composure.",
  "Mrs. Bennet sat looking and winking at me for interrupting you, madam, cried Mr. Collins; but I wish it! Elizabeth made no answer. If they had a mother and daughter.",
  "Charlotte's reply was spared by the strong sisterly partiality which made him courteous. Elizabeth was not quite a settled family there.",
  "Who would have called us in a cause which no one was less difficult to determine not to any young woman without some money. Mrs. Bennet said only, Nonsense, nonsense!",
  "It does seem, and it was a severe disappointment; and, besides, it was all lost upon me.",
  "This information made Elizabeth smile, as she considered that Jane's disappointment had been travelling.",
  "What would I give to hear a conversation in the place, and they parted in silence; and he thought her rather right than pleasant that she had her family under less than a thousand pounds.",
  "On the very relations whom he had formed; but he may not like at all; indeed, nobody can, you know; and it is by no means intend; for he would do me a world of trouble and economy.",
  "Though he had done which satisfied her; his style was not so dreadfully racked as yours seems to be of age, and the eyelashes, so remarkably fine, might be of a young woman of character.",
  "What a fine house richly furnished, said she, after a few minutes conversation together, received them with tolerable tranquillity. I believe.",
  "What he told me was merely accidentally mentioned to Miss Darcy, drawn when she considered how many things have happened! Oh! I will take care.",
  "Well, my dear, said he, taking the disengaged arm of Mr. Bingley! Oh! Elizabeth then contrived to sit alone. Elizabeth found herself considerably useful to both. A great many pretty things.",
  "Mrs. Reynolds then directed their attention to money. Her not objecting does not know how much they were all getting so intimate together.",
  "From the further disadvantage of Lydia's example, she became, by proper attention and management, less irritable, less ignorant, and less insipid. He is also one other person.",
  "James's, with very monotonous solemnity, read three pages, she interrupted him with: Do you prefer reading to cards? And there are such friends!",
  "But it is very pleasing, said Bingley. My character has been my profession--I was brought up at home.",
  "I know not; but circumstances are such that I rejoice in the course of the room. Elizabeth's congratulations were given with a friendly eye.",
  "Elizabeth listened with all his youth there, you know he will not be for ever silent on this unexpected meeting.",
  "At that moment, Sir William Lucas himself appeared, sent by his wife impatiently. You could not but you shall do as little, and think with freedom. That is right.",
  "Will you come down this moment I observed my friend's behaviour attentively; and I trust it does not exactly like her. My dear Miss Elizabeth, you are not going to Brighton.",
  "She highly approved his forbearance, and they began to find that he must mean an allusion to his future situation, he could think of anything else.",
  "You are very cruel, said her father, to send her home when it suited her. I am quite of your younger sisters not worth knowing. Then, observed Elizabeth, you are in very good time. Oh!",
  "Elizabeth's eyes were instantly driven back to what was acknowledged; but she wished her all the arts which ladies sometimes condescend to employ for captivation.",
  "If there is certainly some ingenuity, and I am glad you have been less amiable in my power to prevent its frequently occurring.",
  "That is all to the risk of offending and insulting me, you chose to entertain each other. She wished to see me again, and you write for laughing.",
  "Mrs. Bennet with a conscious smile: very true, said Elizabeth; but without scheming to do. But my dear. I have been exchanged, nothing can be happy! The world is blinded by prejudice?",
  "He still loves me, and the liberty of asking your ladyship whether you were wrong in saying what I esteemed a most delightful evening, a most humiliating picture!",
  "Yes, thought Elizabeth, that would induce you to a woman worthy of being acceptable. No; he never appeared dissatisfied.",
  "Darcy mentioned his letter was soon lost to me; I should persuade you to tell you how it was; everybody says. They walked on, her heart to be killed. Miss Bingley, despises cards."
],
 "tom":
[
  "If Mr. Harbison owned a slave named Bull, Tom would have died, but he said hesitatingly: Becky, I--I don't care for rats much, anyway. Why, he'd kill us some time.",
  "The thought took a swim about every hour, so it was not at all. However, the widow take it to my line. But there was not sure he never done--that.",
  "Everything was auspicious. Least I reckon I ain't afraid. Ten blue tickets equalled a yellow one; for ten yellow tickets the superintendent stood up and sneaked off, crushed and crestfallen.",
  "He tried to amuse himself with the murmur of the as yet un-dreamed-of telegraph; the tale ever so nice. Presently the Welshman stepped out and say something kind and loving; but she thought.",
  "He put his face. This course worked well, and Tom pulled a mile wide, there was a gorgeous triumph; they were well exhausted, they would. So we always do.",
  "That Injun devil wouldn't make any difference whose land it's on. Tom's spelling-book fell under his wig, a perfectly bald and shiny head, he had amassed in selling whitewashing privileges.",
  "The tempest rose higher and higher, and presently the gay assembly. Then he shot the arrow and fell. Every eye sank under his wig, a perfectly bald and shiny head, he had brought.",
  "Huckleberry's hard pantings were his only reply, and the other always remained for the closet, when there ain't anybody dead there yet.",
  "Like many other simple-hearted souls, it was only separated from it by the water-drip. Ain't you and your two-- What!",
  "Huck began to steal sugar under his aunt's very nose, and covered themselves with dust and glory. Well, no--I reckon not! Tom wheeled suddenly and said: How did you dream any more!",
  "It seemed glorious sport to be fond of Pain-killer for the morning and we'll count it and looked around. Without doubt, that was it, he reasoned. We'll explore it again some time, if I'm good.",
  "Yes you did, Sid, said Mary. Huck, have you ever seen one, Huck? His mood always determined his manner. But neither could he on Saturday or Sunday.",
  "I'll float the skiff that bore Judge Thatcher and tried to argue it away till we know Injun Joe's cup stands first in the presence of mind enough to get some blood, and in a skiff.",
  "But hunger and wretchedness rise superior to fears in the cave!",
  "The boys had a theory about the neighborhood of the evening outweighed the uncertain treasure; and, boy-like, he determined to yield his pride and go along too.",
  "The other pirates envied him this majestic vice, and secretly resolved to keep still.",
  "Shut your heads and let them fall helplessly in their laps, and wall their eyes, and heart, and were not considered manly anyway.",
  "NOW to return to civilization--not right now, but-- Tom withered him with his comrades. No answer. They assembled in a skiff. Aunt Polly. I didn't think. That's it!",
  "Mr. Sprague turned himself into a gentle laugh. We'll wait for you. I reckon maybe that's so.",
  "Please don't--I'd be killed, sure--but the widow's been good friends to me that it might have seemed to be drawing nine feet high.",
  "Now go and break her old heart with consternation. The tick tried this, that, and I'll never speak to you. Now, far away from its fastenings and went on digging.",
  "A sweep of chilly air passed by, rustling all the matrons. Then they were well exhausted, they would. What makes you think it was what he wanted to. Cheer up, Becky, and I'm so sorry.",
  "Alfred dropped alongside of him and told them their situation and their troubles. There was a general rush upon the scene. I'm afeard-- I'll give you all to sit up just as Tom said he could bear.",
  "Well, for the bodies had been hid in mighty particular places, Huck--sometimes on islands, sometimes in rotten chests under the bed just in time.",
  "He cried, he pleaded for forgiveness, promised to reform over and the old man; out with derision! So they chose a new disappointment. She said she meant to hold up its head.",
  "Soon he observed that she might die, or lose her reason. That little piece is our last candle! He said under the cross. Presently it occurred to him. Aha! He was so overcome by the great news.",
  "Huck jumped for a moment, but it was a long, narrow, wooded island, with a crowd of their hopes too, when the Pyramids were new; when Troy fell; when the little waifs.",
  "No end of the church; for the night was almost unspeakable.",
  "Tom was a silence and let her hands drop; her face, all glowing with unimaginable splendor. No! The lads searched and researched this place, but they sighed often. He seized Becky's hand and began.",
  "He took a swim about every hour, so it was Friday and concluded to wait a day. I won't be hard to make a world of fun of him as lavishly as it suited him; nobody forbade him to it.",
  "Once more she ventured, and this was a witch that done it. Tom and tell her-- But Sid had snatched his clothes and cleanliness that galled him. I dono--I dono.",
  "The village was suddenly electrified with the thought, and he was about to spring something on the dry, hot sand, and lie there and cover themselves up with his poor wilted flower.",
  "There were a boy, too. If Mr. Harbison owned a slave named Bull, Tom would have driven them home. It's Bull Harbison. How? If she bleeds to death, is that my fault?",
  "I--well, I don't care whose tick he is--he's on my side of the town looking on! Next they wanted to. I dono. Joe said this and held it up for inspection.",
  "And you'll say, Yes, I reckon we can try it? So Tom pried his mouth open and poured out her own transcendent loveliness.",
  "And I don't want to--but what would people say? Oh yes; I saw them downtown and follered them. No, you've always been hateful work in Tom's arms, neither could tell.",
  "Only you don't believe they'll bother us. You don't have to go in a-swimming, Tom? Say, Tom! It's one of them with him. Tom was about to turn the leaves.",
  "He sat looking into her drawn face and she glanced ever so furtively at Tom, but he only endured it--if he even did that much trouble about us. They plunged into the air of one of the woods.",
  "They'll all lie. Huckleberry was cordially hated and dreaded by all the week, and tied the other aisle; he crossed the equator. Without a moment's hesitation he ran to the cave.",
  "But he could do that; but I can't set down, nor lay down, nor roll around anywher's; I hain't got to be ashamed of their lives at present.",
  "And so the imaginary flogging was finished to his throne without saying a word? They ain't got none but these. And what's more, she's getting better, too. So they moved on.",
  "But Mary said, persuasively: Please, Tom--that's a good way; but that Saint Louis smarty that thinks he dresses so fine and is aristocracy! He could lick you till you hear it.",
  "And now he's afraid to proceed to such a romantic feature as the saying is. It was all the group had begged for invitations but Tom said: Lookyhere, Huck, less not try that thing.",
  "He meow'd with caution once or twice and he put the blood to draw something on the ground. Got it at times when no classes were reciting. All right, Huck, it's in my dream. He said: Huck don't need it...",
  "A long, lingering, colossal sigh followed, and then took it up. The inmates were asleep, but it was not an urchin in school! Who's accused you? No, he would lead a life of crime.",
  "He untied the skiff down there, and everywhere hung ragged and abandoned cobwebs. Huck stared at the next instant she had a most melancholy caterwauling.",
  "We will produce the skeleton of that cat. Tom, I hoped you loved me that much, said Aunt Polly entered in time. Petersburg. Is that your knife?",
  "He was very earnest of mien, and very attentive to his heels and had about worn himself out with its arms, and polishing it so. Presently he bethought him of a bow, of course Tom had disappeared.",
  "At recess Tom continued his experiments; grew weary at last, all the time, and he was deeply and gratefully interested in the atmosphere. Not because his troubles now.",
  "The quicker the better--I'm all in actual cash, seemed next to incredible. I can't stand up. No--it's somebody snoring, Tom. We'll get ashore, now. I tell you! Oh, I reckon nobody'll ever know.",
  "The boys seized each others hands and burst out crying with shame and repentance Becky had told in order to employ his tortured faculties.",
  "I judged that twelve had come; they marked where the Adored Unknown lived; he paused a moment; no sound but the enemy to come to follow these fellows, lad? Instantly Tom answered it, and it's right.",
  "Now, Huck, the storm's over, and when she had confessed hardly a week or two the men had reached middle age with an unsatisfied ambition. What!",
  "By and by, and the Sheriff was confident that he would join the Indians, and hunt for us now, Tom. Everything you've ever been seen. Well, that's the trick!",
  "Tom, we can find it. He began to feel a vague possibility. Huckleberry came and took his flogging, along with Joe.",
  "Then conscience granted a truce, and these curiously inconsistent pirates fell peacefully to sleep on the grass, filled with passengers, soon followed.",
  "They cast down their load and began to puff, charily, and with laborious pomp and circumstance--for he was gaining too fast; moved on.",
  "Muff Potter'll hang for this occasion, but it was just the same moment the streets were swarming with frantic half-clad people, who shouted, Turn out! I know it? Yes you did, Sid, said Mary.",
  "Huck searched all the time. He threaded his way back to his feelings, and crying in Tom's eyes, before, but now a difficulty arose--hostile Indians could not help it.",
  "However, this time she had built a fire under him and confessed in his eyes with a slipper in her eye, and gave me a silk thread, and a great log twenty or thirty miles on a spreading oak.",
  "You just keep mum about This and They wish They may Drop down dead in Their Tracks if They ever Tell and Rot. The other place is bad--too common. But he would go plowing the dancing seas, in his chair...",
  "Tom stood looking over the hills and far away, into unknown countries beyond the known ground.",
  "Presently she stopped, and Tom had traded the next day for the stillness and gloom of the heavy time in every direction, and fell to sobbing again. Well, so we did.",
  "Tom, you'll look back, some day, when it's midnight a devil will come, or maybe two thousand, that can open this door night or day, lad! Ah, now you're all right.",
  "Finally he said: I thought there was a noble, a generous, good-hearted soul and honor, I never did see the bait. That's good.",
  "She dropped the water again and go a-fishing? Tom was trembling from head to foot, and began to waver.",
  "Without doubt, that was what she said, Jim. Tom began to quiet down to cry. Least I reckon not, Huck. Don't tell me what it is? He began to show off in high feather, and as soon as he could.",
  "Huck would answer. More visitors came, and went on groaning. It weighed about fifty pounds. Tom was paralyzed; he could not be roused. A thought shot like lightning through Tom's brain.",
  "Please, Becky--I'll whisper it, I'll whisper it ever so long as I was so sorry that I can't set down, nor lay down, nor lay down, nor roll around anywher's; I hain't.",
  "Just as they entered town they agreed to believe she was a-witching him, so he gave a sobbing goodnight and turned around.",
  "But I can't walk more'n a mile, and then added something like burning the bridge between them and civilization. Blame it, I should say so!",
  "It became the absorbing topic of village talk immediately. A very little boy stood up and discovered to bear marks of blood.",
  "The crowd fell apart, now, and as gradually sounds multiplied and life manifested itself. Well, when pap's full, you might take and belt him over that fence, too.",
  "The temptation was too vast to be done very careful; I reckon nobody'll ever know? It is mighty curious, Huck. She started homeward, now, intending to find the marks?",
  "He picked up a straw and began to turn back when he was deeply concerned about the deserted schoolhouse yard, and feeling very miserable.",
  "Tom whistled twice more; these signals were answered in a horror of suspense for his troubled conscience and fears almost persuaded him that life was gone; there was not a single thought.",
  "The night was almost spent. True, he had only reached middle age with an undefined hope that she would! The storm culminated in one of the Seas. And I dreamt that you warn't dead, but only run off.",
  "Hello, Huck! The door was unlocked, a sorrowful sight presented itself in tears. Why, that's awful. About midnight Tom arrived with a burst of silent gratitude.",
  "His arms straightened and stiffened down his sides. That's good enough substitute for coffee. But that's human nature--hurry along, hurry along!",
  "Monday morning always found him visiting the familiar wonders of McDougal's cave. Please, Becky--I'll whisper it, I'll whisper it ever so gay! I ain't used to that old humpbacked Richard.",
  "Well, if I tell you. Each boy said to himself that it was! It's dangerous. Did he say anything? He hoped the boys made cups of broad oak or hickory leaves, and commanded attention.",
  "Tom was eating an apple, and planned the slaughter of more innocents. Yes--the way I'd like to? That's so--that murderin half-breed! It was noticed that they could not help it. Didn't you let him alon...",
  "Children were anxiously questioned, and young teachers. Here was a human! The minister gave out his text and droned along monotonously through an argument that was happening. More's the pity.",
  "That's just like you, Tom, I won't ever get drunk--then you won't tell, will you, Joe? They wished in their best. See? I know now! But they buried him Saturday night? Soon the free world outside.",
  "THE sun rose upon the coffin with a sermon so destructive of all the twelve disciples. There was an easy, comfortable path along the ground. At the end of the other distress.",
  "The weary time dragged on; they slept again, and she grabbed his wig with her little foot and said: Is it genuwyne? Anybody might know that. It done him good, too. Tom quailed. TOM!",
  "The village was thinking and saying commonplace things; moreover, their past history was raked up and submitted. He knew he didn't want to come to Sunday-school?",
  "Tom lay awake and stirring, now; long lances of sunlight pierced down through the woods. She added hot baths, sitz baths, shower baths, and plunges. Hallo, he's stopped!",
  "Describe them--describe them, my boy! However, there was some way that you like it here, don't you, Huck? Then he showed Huckleberry how to proceed. Shucks!",
  "So he thought he would venture to warn laggards and stragglers, and then plunged down as he groped along. I bleeve it's down at the library, by the bedpost, now.",
  "They were about equally represented in the hope that she could hardly endure the misery of fear. People in the ships--make em walk a plank. They're coming, sure.",
  "It was noticed that she had built a fire under him and told them at all, but they conveyed no real cheer. Huckleberry was always willing to go, and be good. By this time.",
  "Oh, he was free and then came decisively down upon the ground, her astonishment was almost spent. This bosom friend sat next him, suffering just as bright as day, now.",
  "If it had gone into savagery, for they shall--for they shall--a--a--shall mourn--a--a--blessed are they that mourn, for they--they-- Sh-- For they--a-- S, H, A-- For they S, H--Oh, I don't know.",
  "AS the earliest suspicion of dawn appeared on Sunday morning, Huck came groping up the pirates. And so forth and so much. They're humans! Oh, if I didn't do us any harm.",
  "Well-a-well, man that is born of woman is of the Red-Handed, and he fell to cheering up the hill. Well--your tooth is loose, but you're not going to tell the upper world about.",
  "He said, with quivering lips and halting utterance: I'll help you. Any fool knows that. Ten blue tickets equalled a red necktie and a deluge of water. I got to be seen with him, or die!",
  "The silences widened; the expectoration marvellously increased. The stillness continued; the master arrived and the circumstances, the surroundings, were in perennial bloom and fluttering with rags.",
  "He gathered quite a group and splashed water in each other's hair and clothes, punched and scratched each other's nose, and covered themselves with dust and glory.",
  "Half an hour later he paused, dripping, upon the peaceful village like a casual stranger whose visit is done. Tom Sawyer find it. This final feather broke the camel's back.",
]};

var text = "Tom stood looking over the hills and far away, into unknown countries beyond the known ground.";

var source = "tom";

var ge = document.querySelector("#mguess span");

ge.textContent = text;

var me = document.querySelector("#mrank");

var total = 0;
var correct = 0;

function dumpGuess(guess) {
var he = document.querySelector("#mhis");
var nr = document.createElement("div");
nr.className="mrow";
var nres = document.createElement("div");
nres.className="mres";
if (guess == source) {
  correct = correct + 1;
  nres.innerHTML = '<i class="fa fa-check mgreen"></i>';
} else {
  nres.innerHTML = '<i class="fa fa-times mred"></i>';
}
nr.appendChild(nres);
var nt = document.createElement("div");
nt.className = "t" + source;
nt.textContent = '"' + text + '"';
nr.appendChild(nt);
he.insertBefore(nr, he.firstChild);
total = total + 1;
if (total == 1) {
me.textContent = "Past guess:";
} else {
me.textContent = "Past " + total + " guesses (success rate " + Math.floor(100 * (correct / total)) + "%):";
}
}

function getRandomInt(min, max) {
  return Math.floor(Math.random() * (max - min)) + min;
}

function nextGuess() {
  source = keys[Math.floor(Math.random()*keys.length)];
  var sentences = data[source];
  var i = Math.floor(Math.random()*sentences.length);
  text = sentences[i];
  ge.textContent = text;
  sentences.splice(i,1);
}

function tomClicked(event)
{
dumpGuess("tom");
nextGuess();
}

function aliceClicked(event)
{
dumpGuess("alice");
nextGuess();
}

function prideClicked(event)
{
dumpGuess("pride");
nextGuess();
}

function mobyClicked(event)
{
dumpGuess("moby");
nextGuess();
}

document.querySelector("#mbtom").onclick = tomClicked;
document.querySelector("#mbalice").onclick = aliceClicked;
document.querySelector("#mbmoby").onclick = mobyClicked;
document.querySelector("#mbpride").onclick = prideClicked;
